title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: 
# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title

